name = "SkansSite"
uuid = "ad41de7a-0f3d-4edc-8844-e8af31a485c7"
authors = ["Rik Huijzer <rikhuijzer@pm.me>"]
version = "0.1.0"

[deps]
Franklin = "713c75ef-9fc9-4b05-94a9-213340da978e"

[compat]
Franklin = "0.10"
